apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agents.fullname" . }}
  labels:
    {{- include "agents.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "agents.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.helm.values.global.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.helm.values.secrets.vault.enabled }}
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: {{ .Values.helm.values.secrets.vault.role | quote }}
        {{- end }}
      labels:
        {{- include "agents.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.helm.values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "agents.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.helm.values.image.repository }}:{{ .Values.helm.values.image.tag }}"
          imagePullPolicy: {{ .Values.helm.values.image.pullPolicy }}
          {{- if .Values.helm.values.command }}
          command:
            {{- toYaml .Values.helm.values.command | nindent 12 }}
          {{- end }}
          {{- if .Values.helm.values.args }}
          args:
            {{- toYaml .Values.helm.values.args | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.helm.values.networking.internalPort }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.helm.values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if .Values.helm.values.metadata.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.helm.values.metadata.livenessProbe.path }}
              port: http
            failureThreshold: {{ .Values.helm.values.metadata.livenessProbe.failureThreshold }}
            periodSeconds: {{ .Values.helm.values.metadata.livenessProbe.probeInterval }}
          {{- end }}
          {{- if .Values.helm.values.metadata.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.helm.values.metadata.readinessProbe.path }}
              port: http
            failureThreshold: {{ .Values.helm.values.metadata.readinessProbe.failureThreshold }}
            periodSeconds: {{ .Values.helm.values.metadata.readinessProbe.probeInterval }}
          {{- end }}
          resources:
            requests:
              cpu: {{ .Values.helm.values.min.cpu }}
              memory: {{ .Values.helm.values.min.memory }}
            limits:
              cpu: {{ .Values.helm.values.max.cpu }}
              memory: {{ .Values.helm.values.max.memory }}
