apiVersion: v1
kind: Service
metadata:
  name: {{ include "agents.fullname" . }}
  labels:
    {{- include "agents.labels" . | nindent 4 }}
    {{- with .Values.helm.values.metadata.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.helm.values.networking.serviceType }}
  ports:
    - port: {{ .Values.helm.values.networking.externalPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "agents.selectorLabels" . | nindent 4 }}
